### ISSUE TITLE
Use afterEvaluate, not projectsEvaluated

### ISSUE THREAD

**Issue by oehme** [jponge/vertx-gradle-plugin#1]
https://github.com/jponge/vertx-gradle-plugin/blob/d86d2c37ecf476ad1fee028235d73888fd05b944/src/main/kotlin/io/vertx/gradle/VertxPlugin.kt#L47

`projectsEvaluated` is only called after *all* projects have been evaluated. Plugins that want to react to user input should generally react to `Project.afterEvaluate` instead, which runs right after that specific project is evaluated.

**Comment by jponge** [comment]
👍
