### ISSUE TITLE
Rename "fat" classifier to other value?

### ISSUE THREAD

**Issue by amdelamar** [jponge/vertx-gradle-plugin#10]
First of all, nice plugin! 😃 

Running `./gradlew build` produces the `build/libs/myapp-1.0-fat.jar`...

Any way to rename the "fat" classifier to something else?

I have tried this, from the [shadow docs](http://imperceptiblethoughts.com/shadow/#configuring_output_name)
```groovy
shadowJar {
   baseName = 'myapp' // works
   classifier = null // doesnt work
   version = '1.0' // works
}
```
but that didn't work.

If I create a separate project with only the `shadow v2.0.0` plugin, the `classifier` works correctly. So maybe the version your plugin uses is older?

**Comment by spodin** [comment]
@amdelamar While this issue stays open - may be `archiveName` can do the trick for you?

```
shadowJar {
    archiveName = "${project.name}-${project.version}-uber.jar"
}
```

**Comment by amdelamar** [comment]
**Yep. That works, thanks!**

After inspecting a bit, seems there are two _published_ versions of shadow plugin? ( [2.0.0](https://plugins.gradle.org/plugin/com.github.johnrengelman.plugin-shadow) and [2.0.1](https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow))

The [shadow docs](http://imperceptiblethoughts.com/shadow/) mention 2.0.1 but also that `classifier` is a valid option. Kinda confusing. 😕 Maybe this isn't a vertx-plugin problem anymore.

**Comment by jponge** [comment]
It doesn't look like a plugin issue to me indeed, but perhaps this should be documented, what do you think?

**Comment by pflima92** [comment]
Hey @jponge just take the discussion, currently the gradle are notifying one warning when using the shadowJar

Registering invalid inputs and outputs via TaskInputs and TaskOutputs methods has been deprecated and is scheduled to be removed in Gradle 5.0.

Using TaskInputs.file() with something that doesn't resolve to a File object has been deprecated and is scheduled to be removed in Gradle 5.0. Use TaskInputs.files() instead.

**Comment by jponge** [comment]
​Yes, I'm aware of this warning with the shadow task.

**Comment by amdelamar** [comment]
Closing now, as spodin provided a workaround. Thanks.
