### ISSUE TITLE
Don't overwrite sourceCompatibility

### ISSUE THREAD

**Issue by oehme** [jponge/vertx-gradle-plugin#2]
The source compatibility is currently set in an `afterEvaluate` block, overwriting whatever the user specified. It should be set before evaluation instead, so it is a default that the user can adjust.

**Comment by jponge** [comment]
👍

**Comment by karolhor** [comment]
Hi, is it possible to reopen this issue? I can help with PR.

IMO this plugin shouldn't take responsibility for setting sourceCompatibility at all. I think it should setup vertx part.

**Comment by jponge** [comment]
Hi, it sets a 1.8 version by default, why is that an issue?

**Comment by karolhor** [comment]
I have multi module gradle project. My `common` module is set to Java 11 version and it is not compatible with my vertx module where I'm using your plugin. 

Is it really necessary to force Java version in vertx plugin?

**Comment by jponge** [comment]
Agreed

**Comment by karolhor** [comment]
That's great. Would you like to add configuration field for sourceCompatibility in `vertx` plugin or remove this part of code. I think that it's not necessary to duplicate code from `java` section but this is your decision.

**Comment by jponge** [comment]
Yes it is best to let it be a `java { ... }` configuration thing.
