### ISSUE TITLE
Use plugin with Heroku deployment

### ISSUE THREAD

**Issue by RdeWilde** [jponge/vertx-gradle-plugin#50]
Can I use this `vertx`/`vertxRun` option with heroku deployment?

Currently I have registered it like this:
```
// Heroku
tasks.register("stage") {
    dependsOn("build", "vertxRun")
}
```

But I'm pretty unsure if this is the way to go.
Maybe it is better to run some kind of command from Procfile?

https://devcenter.heroku.com/articles/deploying-gradle-apps-on-heroku

**Comment by jponge** [comment]
You may try this indeed.
