### ISSUE TITLE
Is it possible to deploy multiple verticles?

### ISSUE THREAD

**Issue by RdeWilde** [jponge/vertx-gradle-plugin#51]
In the current configuration I can define a main verticle. But would it also be possible to deploy a list of verticles?

Additionally, would it be possible to define the number of instances per verticle?
https://vertx.io/docs/vertx-core/java/#_specifying_number_of_verticle_instances

(Also interesting to integrate https://vertx.io/docs/vertx-core/java/#_specifying_number_of_verticle_instances)

**Comment by jponge** [comment]
The classic pattern is that your  _main_ verticle deploys the other verticles.

You may also look at https://github.com/jponge/vertx-boot (quite simple)
