### ISSUE TITLE
Use JavaExec.mainClass instead of JavaExec.main

### ISSUE THREAD

**Issue by k-mack** [jponge/vertx-gradle-plugin#56]
Gradle 7 deprecates `JavaExec.main` in favor of  `JavaExec.mainClass`.
Using this plugin with Gradle 7 emits the following warning:

```
$ ./gradlew --warning-mode=all help

The JavaExec.main property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the mainClass property instead. See https://docs.gradle.org/7.1.1/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:main for more details.
```

**Comment by rjaros** [comment]
The plugin doesn't work with Gradle 8 because this fix was not released. Any chance of the new release?

**Comment by jponge** [comment]
I'll have a look

**Comment by jponge** [comment]
I've pushed a 1.4.0 release, looks like Gradle folks will need to review before it's public
