### ISSUE TITLE
Please publish 1.4.0 to the Maven Repository

### ISSUE THREAD

**Issue by jdev-2020** [jponge/vertx-gradle-plugin#70]
The new version 1.4.0 can't be found on the [Maven Repository](https://mvnrepository.com/artifact/gradle.plugin.io.vertx/vertx-gradle-plugin).

**Comment by jponge** [comment]
It's been published to the Gradle plugins portal.

**Comment by jdev-2020** [comment]
Thanks for looking at this.

Having the plugin published to the Gradle Plugins Portal works when we apply it on the project with:

```
plugins {
  id 'io.vertx.vertx-plugin' version '1.4.0'
}
```

But it won't work if we depend on the plugin as a dependency:

```
dependencies {
  implementation 'gradle.plugin.io.vertx:vertx-gradle-plugin:1.4.0'
}
```

Gradle build fails with:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':myproject'.
>    \> Could not resolve all task dependencies for configuration ':myproject:classpath'.
>       \> Could not find gradle.plugin.io.vertx:vertx-gradle-plugin:1.4.0.
>         Searched in the following locations:
>           - https://plugins.gradle.org/m2/gradle/plugin/io/vertx/vertx-gradle-plugin/1.4.0/vertx-gradle-plugin-1.4.0.pom

It used to work with the version 1.3.0 of the plugin.
I believe that the publication will make it work for 1.4.0.

**Comment by jponge** [comment]
You can probably use https://plugins.gradle.org/m2/ as a Maven repository.

**Comment by jdev-2020** [comment]
It didn't work with

```
repositories {
  maven {
    url 'https://plugins.gradle.org/m2/'
  }
}
dependencies {
  implementation 'gradle.plugin.io.vertx:vertx-gradle-plugin:1.4.0'
}
```
https://plugins.gradle.org/m2/gradle/plugin/io/vertx/vertx-gradle-plugin/1.4.0/vertx-gradle-plugin-1.4.0.pom is 404.

**Comment by jponge** [comment]
You should open a ticket on Gradle then, I don't know what is their current strategy for consuming plugins as dependencies instead of in the classic plugins block.

On Mon, Mar 13, 2023, at 23:29, jdev-2020 wrote:
> 
> 
> It didn't work with
> 
> `repositories {
>   maven {
>     url 'https://plugins.gradle.org/m2/'
>   }
> }
> dependencies {
>   implementation 'gradle.plugin.io.vertx:vertx-gradle-plugin:1.4.0'
> }
`

**Comment by jdev-2020** [comment]
It looks like Gradle changed the naming. This works:

```
 dependencies {
   implementation 'io.vertx:vertx-gradle-plugin:1.4.0'
 }
```

Thank you.
